name: m2
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  dotted_border: ^2.0.0+3
  flutter:
    sdk: flutter
  flutter_braintree: ^3.0.0
  flutter_mobx: ^2.0.6+5
  flutter_portal: ^1.1.3
  flutter_rating_bar: ^4.0.1
  flutter_spinkit: ^5.1.0
  flutter_svg: ^2.0.0+1
  flutter_widget_from_html: ^0.14.11
  fluttertoast: ^8.2.4
  font_awesome_flutter: ^10.3.0
  go_router: ^13.2.0
  graphql_flutter: ^5.1.2
  http: ^1.1.2
  intl: ^0.19.0
  mobx: ^2.1.3
  page_transition: ^2.0.9
  provider: ^6.0.5
  razorpay_web: ^1.4.2
  shared_preferences: ^2.0.15
  shimmer: ^3.0.0
  url_launcher: ^6.1.7
  webview_flutter: ^4.7.0

  gql: any
dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^3.0.1
  flutter_native_splash: ^2.2.17
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.1.1

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/images/logo.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/svg/
    - assets/src/
    - assets/rive/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
